### ISSUE TITLE
HUD + Keybinds do not properly save 

### ISSUE THREAD

**Issue by KadTheHunter** [betterclient/SnapTapMC#1]
Issue: HUD and Keybinds do not properly save between launches.

Expected Behavior: HUD and Keybinds should remember their states between launches

Steps to Reproduce:
- Open Minecraft with SnapTap
- Unbind or Modify the Keybinds
- Enter a world and disable the HUD
- Close Minecraft
- Re-launch Minecraft
- The keybinds will be rebound to the defaults, and the HUD will be re-enabled

**Comment by KadTheHunter** [comment]
This issue is in regards to SnapTaps own keybinds and HUD.

**Comment by betterclient** [comment]
i couldnt recreate the keybinds being rebound to defaults

**Comment by betterclient** [comment]
maybe its another mod?

**Comment by KadTheHunter** [comment]
>i couldnt recreate the keybinds being rebound to defaults
>maybe its another mod?

It's not another mod, I just recreated this on a fresh instance with nothing but SnapTap and Fabric API installed.

Full Steps to Reproduce:
- Create fresh instance, w/SnapTap + Fabric API
- Change SnapTaps keybinds, and disable SnapTaps HUD
- Close and re-open game
- SnapTaps keybinds and HUD are reset to default states.

You will have to create a world to test the HUD being re-enabled of course. Same steps as in my first post.

Maybe you forgot to close and re-open the game, and just left and rejoined a world instead?

**Comment by betterclient** [comment]
I in fact did re-open the game. A day later, a fresh restart to my machine and my keybinds are still the ones I set them to.
As for hud, its was a known issue already, i already have the fix, I'm waiting to fix the other "issue".

**Comment by KadTheHunter** [comment]
Well then I'm not sure what else to say. One of us is doing something wrong, and I don't think it's me.

I just tested it again, created a fresh instance with nothing but SnapTap + Fabric API, rebound SnapTaps keys from F7/F8 to B/N, closed the game, reopened it, and they're rebound to F7/F8.

Attached below is a video showing the entire process, and proving it gets reset.

https://github.com/user-attachments/assets/f5b55696-07c5-4776-bed0-8485d78d43a0

**Comment by betterclient** [comment]
oh, well you see i thought by keybinds you meant the WASD keys, fixed now, sorry.
